products = [
    {
        "name": "Mặt bích nhớt hộp rùa đến van thủy lực phía sau 5018 4018 3218",
        "Description": "",
        "category_id":6,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Mặt bích + Coren nhớt hộp rùa máy kéo 4508",
        "Description": "",
        "category_id": 6,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
        
    },
    {
        "name": "Mặt bích nhớt + 2 coren máy kéo 3408",
        "Description": "",
        "category_id":6,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
       
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L32/4018 Kubota",
        "Description": "",
        "category_id": 7,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L5018 Kubota",
        "Description": "",
        "category_id": 7,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L31/3408 Kubota",
        "Description": "",
        "category_id": 7,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L4508 Kubota",
        "Description": "",
        "category_id": 7,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L3218/4018 Kubota",
        "Description": "",
        "category_id": 8,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L5018 Kubota",
        "Description": "",
        "category_id": 8,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L31/l3408 Kubota",
        "Description": "",
        "category_id": 8,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L4508 Kubota",
        "Description": "",
        "category_id": 8,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Cảo càng hướng DC70",
        "Description": "",
        "category_id": 11,
        "quantity": 30,
        "price": 450000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Dụng cụ ép lò xo chuyển hướng",
        "Description": "",
        "category_id": 11,
        "quantity": 30,
        "price": 150000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Tay Tuýp cân lực xiết ốc",
        "Description": "",
        "category_id": 11,
        "quantity": 30,
        "price": 900000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI quạt gió két nước RF3405",
        "Description": "",
        "category_id": 12,
        "quantity": 30,
        "price": 111000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT,C59) 0kg 2",
        "Description": "",
        "category_id": 12,
        "quantity": 30,
        "price": 930000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, BỘ Đập (V-BELT,C52) 0kg 2",
        "Description": "",
        "category_id": 12,
        "quantity": 30,
        "price": 830000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT,B107) 0kg 1",
        "Description": "",
        "category_id": 12,
        "quantity": 30,
        "price": 240000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, HST (BELT,V) 0.000kg 2) 0kg 2",
        "Description": "",
        "category_id": 13,
        "quantity": 30,
        "price": 930000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, BỘ ĐẾM (COG-BELT,V,C54,COUNTER) 0.000kg 2) 0kg 2",
        "Description": "",
        "category_id": 13,
        "quantity": 30,
        "price": 830000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (BELT,V) 0.000kg 1",
        "Description": "",
        "category_id": 13,
        "quantity": 30,
        "price": 240000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT(FAN,38REC)) 0.05kg 1",
        "Description": "",
        "category_id": 14,
        "quantity": 30,
        "price": 80000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT(C63)) 0.4kg 1",
        "Description": "",
        "category_id": 14,
        "quantity": 30,
        "price": 769000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V,CỤM (V-BELT,ASSY) 0.4kg 1",
        "Description": "",
        "category_id": 14,
        "quantity": 30,
        "price": 100000,
        "discount_id": 0,
        "image": "",

    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT) 0kg 1",
        "Description": "",
        "category_id": 14,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    }
]

module.exports = products;