let products = [
    {
        "name": "Mặt bích nhớt hộp rùa đến van thủy lực phía sau 5018 4018 3218",
        "Description": "",
        "category_id":1,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Mặt bích + Coren nhớt hộp rùa máy kéo 4508",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
        
    },
    {
        "name": "Mặt bích nhớt + 2 coren máy kéo 3408",
        "Description": "",
        "category_id":1,
        "quantity": 30,
        "price": 390000,
        "discount_id": 0,
        "image": "",
       
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L32/4018 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L5018 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L31/3408 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 1 tay + phụ kiện phù hợp cho máy kéo L4508 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2180000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L3218/4018 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L5018 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L31/l3408 Kubota",
        "Description": "",
        "category_id": 1,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Bộ Van 2 tay và phụ kiện phù hợp cho máy kéo L4508 Kubota",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 2480000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Cảo càng hướng DC20",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 450000,
        "discount_id": 0,
        "image": ""
    },
    {
        "name": "Dụng cụ ép lò xo chuyển hướng 2",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 150000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Tay Tuýp cân lực xiết ốc lớn",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 900000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI quạt gió két nước RF3405",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 111000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT,C59) 0kg 2",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 930000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, BỘ Đập (V-BELT,C52) 0kg 2",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 830000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT,B102) 0kg 1",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 240000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, HST (BELT,V) 0.000kg 2) 0kg 2",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 930000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V, BỘ ĐẾM (COG-BELT,V,C54,COUNTER) 0.000kg 2) 0kg 2",
        "Description": "",
        "category_id": 2,
        "quantity": 30,
        "price": 830000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (BELT,V) 0.000kg 1",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 240000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT(FAN,38REC)) 0.05kg 1",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 80000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT(C13)) 0.4kg 1",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 219000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "DÂY ĐAI CHỮ V,CỤM (V-BELT,ASSY) 0.4kg 1",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 100000,
        "discount_id": 0,
        "image": "",

    },
    {
        "name": "DÂY ĐAI CHỮ V (V-BELT) 0kg 1",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Bộ cầu chì máy gặt DC70",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Bộ cầu chì đủ bộ cho máy kéo Kubota 5018 4018 3218 (miễn phí ship)",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Cảo càng hướng DC70",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dụng cụ ép lò xo chuyển hướng",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Tay Tuýp cân lực xiết ốc",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Đồng hồ nhiệt dạng kim",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nguồn xạc pin điện thoại",
        "Description": "",
        "category_id": 3,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Bộ đồng hồ đo áp suất nhớt",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SC59 Động cơ đến hộp số HST",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SC96 Buồng đập",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SB104 Trục khoan lúa",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SB66 Lắc sàng",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa W800-SB54 Đóng gặt",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SB46 Trả nghẹn",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dây curoa SB107 Guồng cào",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Bộ đồng hồ đo áp suất nhớt Hàn",
        "Description": "",
        "category_id": 4,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nhớt động cơ 4 kỳ SAE 15W-40 (4 lit)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nhớt động cơ 4 kỳ SAE 15W-40 (10 lit)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nhớt động cơ 4 kỳ SAE 15W-40 (20 lit)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nhớt Thủy lực UDT (10 lit)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Nhớt Thủy lực UDT (20 lit)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Mỡ Bôi Trơn (Tube 0.4 kg)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Dung dịch giải nhiệt đông cơ KUBOTA (Can 2 lít)",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Lọc nhớt động cơ ô tô",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Lọc nhớt động cơ xe máy",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Lọc nhiên liệu",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    },
    {
        "name": "Lọc tách nước",
        "Description": "",
        "category_id": 5,
        "quantity": 30,
        "price": 395000,
        "discount_id": 0,
        "image": "",
    }
];

let path = 'public/images/';
for(let i = 0; i < products.length; ++i) {
    products[i]["image"] = path + 'p' + (Math.floor(Math.random() * 14) + 1) + '.jpg';
};

module.exports = products;